QtiGralloc: Remove an unused variable
hardware/qcom/display/gralloc/QtiGralloc.cpp:188:14: error: unused variable 'p' [-Werror,-Wunused-variable]
  qti_ycbcr *p = reinterpret_cast<qti_ycbcr *>(in.data());
             ^
1 error generated.